### ISSUE TITLE
Wikis that have dumps (e.g. wikimedia ones)

### ISSUE THREAD

**Issue by blester125** [r-three/common-pile#1]
Several datasets some from Wikimedia sources and they provide data dumps. These dumps contain wikitext markup which can be parsed with libraries like [wtf_wikipedia](https://github.com/spencermountain/wtf_wikipedia).

- [ ] Wikipedias (Encyclopedia)
  - ~10m pages
  - ~100 languages
  - Moderated
  - meta-dump includes "talk" pages
- [ ] Wikinews (News)
  - ~10k pages
  - ~10 languages
  - Moderated
- [ ] Wikibooks (Textbooks)
  - ~100k pages
  - ~10 languages
  - Moderated
- [ ] Wikitravel/Wikivoyage (Travel guides) 
  - ~100k pages
  - ~10 languages
  - Moderated
- [ ] Wikisource (old stuff)
  - ~100k pages
  - ~10 languages
  - Moderated
- [ ] Wikiversity (Learning Resources/Textbooks)
  - ~100k pages
  - ~ 10 languages 
  - Moderated
- [ ] Wikipedia Talk Pages (Dialog-ish)
  - ~1m pages?
  - ~100 languages?
  - Not Moderated
  -  Some hate speech/noise

**Comment by conceptofmind** [comment]
> @conceptofmind was also asking me about mediawiki parsing, so maybe coordinate to make sure you aren't overlapping work. The main thing we discussed was that I suggested using ncermountain/wtf_wikipedia plus a little bit of postprocessing.

Will talk to Shayne and Luca to ensure that there is no overlap on this.

**Comment by shayne-longpre** [comment]
https://github.com/spencermountain/wtf_wikipedia

**Comment by conceptofmind** [comment]
https://github.com/spencermountain/dumpster-dip/issues/4

**Comment by blester125** [comment]
Subsumed into https://github.com/r-three/common-pile/issues/82
