### ISSUE TITLE
Printables and Similar Sites

### ISSUE THREAD

**Issue by blester125** [r-three/common-pile#15]
Domain: Descriptions of 3d models for 3d printers

Each model includes license information on the page and the TOS says that the text description counts as part of the "print documents" so it should be under the same license.

The TOS of printables.com says no scraping, but we might be able to email them to get a dump.

- [ ] printables.com
- [ ] thingiverse.com
- [ ] makerworld.com (Bambu Labs, they have a feud with printables and are probably why they added no scraping to the TOS)

**Comment by StellaAthena** [comment]
@blester125 How much text is there here? Also, if the text is just a description of the objects I'm worried it's low-information without the context of the object as well.

**Comment by blester125** [comment]
Data would probably be small and a lot of parsing would need to be done to maximize text so probably not worth looking into it for now
