### ISSUE TITLE
Global News

### ISSUE THREAD

**Issue by blester125** [r-three/common-pile#17]
Domain: Multilingual news

See globalvoices.org

Need to scrape and parse the HTML

**Comment by conceptofmind** [comment]
I'll check this one out.

**Comment by conceptofmind** [comment]
Should be able to just get the sitemap hopefully and hit with trif + post proc.

**Comment by conceptofmind** [comment]
https://globalvoices.org/feeds/

**Comment by conceptofmind** [comment]
```
When you share, republish or translate our stories, you must include a link to the original Global Voices story and the name of the author at the top of the republished post.

We have numerous reciprocal republication partnerships with websites in different languages. If you would like to republish our stories regularly or under special terms, please [contact us.](https://globalvoices.org/contact)
```

**Comment by StellaAthena** [comment]
> ```
> When you share, republish or translate our stories, you must include a link to the original Global Voices story and the name of the author at the top of the republished post.
> 
> We have numerous reciprocal republication partnerships with websites in different languages. If you would like to republish our stories regularly or under special terms, please [contact us.](https://globalvoices.org/contact)
> ```
> 
> We likely are not going to want the text formatted as such. I will send them an email.

Any updates?

**Comment by conceptofmind** [comment]
Have not heard anything. Will do a followup

**Comment by blester125** [comment]
Many news sources have been scrapped and processed with our codebase and additional news sources are tracked in #44, closing this one
