### ISSUE TITLE
Wikis that don't have dumps (i.e. non-wikimedia ones) and need scraping

### ISSUE THREAD

**Issue by blester125** [r-three/common-pile#7]
Domain: Encyclopedia (Wikia)/various (Fandom wiki's)
~10m pages
~10 languages
Partially Moderated, Has some hate speech/noise

Would need to scrape the pages as there isn't a dump. There should be a URL parameter that allows one to get the wikitext version. These wikis will probably also have "talk" pages, those should be included.

Marked "done" on the sheet, need to get the code/dump from Adam

Fandom wikis are wikis created by users for information about things videogames, etc.

- [ ] Wikia
- [ ] Fandom Wikis
  - [ ] Example
  - [ ] Example Talk Pages
- [ ] Ballotpedia (Encyclopedia about American Politics)
- [ ] localwiki (Encyclopedia about "local knowledge" in the US)
- [ ] Proofwiki

**Comment by blester125** [comment]
Not sure if the best way to vet this kind of thing, but it does seem like there is some stuff in fandom-wiki's that aren't really CC Licensed. For example, [The Elder Scrolls Wiki](https://elderscrolls.fandom.com/wiki/The_Elder_Scrolls_Wiki) has the full text for dialogue trees in them ([example](https://elderscrolls.fandom.com/wiki/Missing_in_Action).

As these are written by Bethesda, I'm sure they aren't actually cc/by-sa which the wiki page says they are

**Comment by haileyschoelkopf** [comment]
Hi @blester125 ! 

> Not sure if the best way to vet this kind of thing, but it does seem like there is some stuff in fandom-wiki's that aren't really CC Licensed. For example, [The Elder Scrolls Wiki](https://elderscrolls.fandom.com/wiki/The_Elder_Scrolls_Wiki) has the full text for dialogue trees in them ([example](https://elderscrolls.fandom.com/wiki/Missing_in_Action).
As these are written by Bethesda, I'm sure they aren't actually cc/by-sa which the wiki page says they are

is this still a pressing issue? I'd be happy to try to read through some of this collected data and vet it for similar wholesale-lifted content / consider how to filter it if it is. Can't seem to find code or data for this source in a branch anywhere though.

If it's not the most pressing thing or you've got it handled, I'll check out another issue instead!

**Comment by lintangsutawika** [comment]
Can take a look. Atleast wikis listed here that are based on mediawiki should be able to reuse code from #51 .

The ones based on fandom have downloadable dumps. The others would require manual scraping, it seems.

**Comment by blester125** [comment]
How many wiki's are there that don't use mediawiki (and would need html scraping)?

**Comment by craffel** [comment]
OTOH the only large source of non-mediawiki wikis is wikidot, which actually uses its own markup etc. so should be treated separately. Does your scraper work with all the wikis you mentioned in https://github.com/r-three/licensed-pile/issues/7#issue-1980372542 and https://github.com/r-three/licensed-pile/issues/7#issuecomment-1804209709?

**Comment by lintangsutawika** [comment]
The large source ones are either wikidot or Fandom like wowpedia and wokiepedia ( I don't know if this is actually just mediawiki since it seems similar https://community.fandom.com/wiki/Help:Database_download)

Few wikis already have dumps.
- [Appropedia](https://www.appropedia.org/approbackups/currentdump.xml.gz)
- [Encyclopedia of Mathematics](https://encyclopediaofmath.org/wiki/Talk:EoM:This_project/Archive_1)

**Comment by storytracer** [comment]
The Internet Archive has an aggregate collection called [WikiTeam](https://archive.org/details/wikiteam), which was created and populated by [ArchiveTeam](https://en.wikipedia.org/wiki/Archive_Team) and includes over 600,000 wikis as well as entire Wikifarms, i.e. Wiki hosting platforms featuring many small wikis, some of which have already been offline for years. See the ArchiveTeam documentation here: https://wiki.archiveteam.org/index.php/WikiTeam.

To filter for permissively licensed queries, you can this IA search query: `licenseurl:(*\/by\/* OR *\/by-sa\/* OR *publicdomain*)`. The same query works across all IA collections, but in some collections the metadata field isn't really populated. The query for WikiTeam returns [325,246 permissively licensed results](https://archive.org/details/wikiteam?tab=collection&query=licenseurl%3A%28*%5C%2Fby%5C%2F*+OR+*%5C%2Fby-sa%5C%2F*+OR+*publicdomain*%29).

**Comment by craffel** [comment]
Ah, this is amazing. We should double check that this covers the wikis we know of. I guess one issue is that these scrapes are out-of-date, but we can use it as an easy fallback.

**Comment by storytracer** [comment]
The WikiTeam scrapes are not necessarily out-of-date, the WikiTeam project is active and the IA collection was updated as late as two weeks ago: https://archive.org/details/wikiteam?tab=collection&sort=-date. Also, we can always use [WikiTeam's dumping tool](https://github.com/mediawiki-client-tools/mediawiki-dump-generator) to scrape wikis which we want a recent dump of or which are not yet included in the WikiTeam collection to make our dumps compatible with the WikiTeam dumps. The great benefit of the WikiTeam collection, however, is that it also contains historical data, i.e. defunct and offline wikis!

The cherry on top is [WikiIndex.org](https://wikiindex.org/) which is mentioned in the [ArchiveTeam Wiki page for WikiTeam](https://wiki.archiveteam.org/index.php/WikiTeam#References). WikiIndex is a meta-wiki which lists more than 20K+ wikis including the description, the used engine and license (sic!) for each wiki. Of course WikiIndex is also machine-readable [through an API](http://wikiindex.org/api.php) and there is a fairly recent WikiIndex dump from Sep 2023 uploaded to archive.org: https://archive.org/details/wiki-wikiindex.org-20230919.

**Comment by blester125** [comment]
Subsumed into https://github.com/r-three/common-pile/issues/82
