### ISSUE TITLE
Patent Data

### ISSUE THREAD

**Issue by blester125** [r-three/common-pile#9]
Domain: Patents

Can we use the Google Patents data for this?

It might be possible to use C4/Common Crawl data for this as `patents.google.com` is one of the most represented domains in c4

**Comment by chris-ha458** [comment]
Would this be relevant in this context?

https://www.uspto.gov/learning-and-resources/bulk-data-products

**Comment by chris-ha458** [comment]
https://bulkdata.uspto.gov/
I'll take a look into some of those sets.

**Comment by chris-ha458** [comment]
If this line of inquiry is fruitful, the following might be useful as well.

It ostensibly combines multiple countries datasets and multiple other patent datasets as well.
However, I do not have a proper GCP account (which is necessary for the queries and even the queries cost money) so I'd appreciate input from somebody familiar with GCP / GCP datasets
https://console.cloud.google.com/marketplace/product/google_patents_public_datasets/google-patents-public-data?pli=1&project=api-project-904060009868

**Comment by StellaAthena** [comment]
@sunnydigital @chris-ha458 any updates on this?

**Comment by sunnydigital** [comment]
> @sunnydigital @chris-ha458 any updates on this?

Hi Stella, I'm no longer working on this project. Let me unassign myself.

**Comment by baberabb** [comment]
> If this line of inquiry is fruitful, the following might be useful as well.
> 
> It ostensibly combines multiple countries datasets and multiple other patent datasets as well. However, I do not have a proper GCP account (which is necessary for the queries and even the queries cost money) so I'd appreciate input from somebody familiar with GCP / GCP datasets https://console.cloud.google.com/marketplace/product/google_patents_public_datasets/google-patents-public-data?pli=1&project=api-project-904060009868

Had a look and they only have text available for US publications. Other countries just have (v. short) abstracts, from what I could tell.

**Comment by chris-ha458** [comment]
@baberabb can you share how you accessed it?
Did it require GCP credits?

@StellaAthena I do think this is a plausible pathway, but I am not able to spearhead it at the moment. I will try to assist any effots though.

**Comment by baberabb** [comment]
> @baberabb can you share how you accessed it? Did it require GCP credits?

Yes! charged me $20 and I just made a few requests. I think if you still have free GCP credits then you can use that after activating billing.
